-- DNTL ART / Cinema game catalogue
-- Canonical schema applied to Supabase project tlyczyfsboqrtrdpwizp.
-- Game clients receive SELECT only; user/game progress remains localStorage in the demo.

create table if not exists public.cinema_sources (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  source_url text,
  methodology text not null,
  license_note text,
  is_public_source boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.cinema_movies (
  id bigint generated by default as identity primary key,
  canonical_key text not null unique,
  title text not null,
  year int check (year between 1888 and 2100),
  director text,
  country text,
  runtime_min int,
  genres text[] not null default '{}',
  imdb_id text,
  wikidata_id text,
  image_url text,
  image_source_url text,
  symbol text not null default '◆',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cinema_rankings (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text,
  source_id bigint references public.cinema_sources(id) on delete restrict,
  category text not null,
  year_from int,
  year_to int,
  ranking_method text not null,
  snapshot_date date not null default current_date,
  max_items int not null default 50 check (max_items between 1 and 500),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.cinema_ranking_items (
  ranking_id bigint not null references public.cinema_rankings(id) on delete cascade,
  movie_id bigint not null references public.cinema_movies(id) on delete cascade,
  rank_position int not null check (rank_position > 0),
  score numeric,
  votes bigint,
  evidence jsonb not null default '{}'::jsonb,
  primary key (ranking_id, movie_id),
  unique (ranking_id, rank_position)
);

create index if not exists cinema_movies_year_idx on public.cinema_movies(year);
create index if not exists cinema_movies_genres_gin on public.cinema_movies using gin(genres);
create index if not exists cinema_rankings_category_idx on public.cinema_rankings(category, year_from, year_to);
create index if not exists cinema_rankings_source_id_idx on public.cinema_rankings(source_id);
create index if not exists cinema_ranking_items_rank_idx on public.cinema_ranking_items(ranking_id, rank_position);
create index if not exists cinema_ranking_items_movie_id_idx on public.cinema_ranking_items(movie_id);

alter table public.cinema_sources enable row level security;
alter table public.cinema_movies enable row level security;
alter table public.cinema_rankings enable row level security;
alter table public.cinema_ranking_items enable row level security;

-- Public catalogue reads are intentional. No INSERT/UPDATE/DELETE policy is granted to browser roles.
create policy "public read cinema sources" on public.cinema_sources for select to anon, authenticated using (true);
create policy "public read cinema movies" on public.cinema_movies for select to anon, authenticated using (true);
create policy "public read cinema rankings" on public.cinema_rankings for select to anon, authenticated using (true);
create policy "public read cinema ranking items" on public.cinema_ranking_items for select to anon, authenticated using (true);

grant select on public.cinema_sources, public.cinema_movies, public.cinema_rankings, public.cinema_ranking_items to anon, authenticated;

-- Initial dataset in production:
--   imdb-most-voted-2000-2026 (50 films)
-- plus genre slices for Action, Adventure, Animation, Comedy, Crime, Drama, Sci-Fi and Thriller.
-- The ordering is DNTL-derived: IMDb num_votes DESC; average_rating is evidence only.
-- It is NOT the official IMDb Top 250.
